version: '3.0'
services:
  # gitlab-runner:
  #   image: gitlab/gitlab-runner:latest
  #   restart: always
  #   volumes:
  #     - gitlab-runner-config:/etc/gitlab-runner
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - /etc/localtime:/etc/localtime:ro
  postgres:
    container_name: media-organizer
    image: postgres:15.4
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '5436:5432'
      # - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "9000:9000"
