name: Go CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build & exit on test-flag
        run: |
          cd src
          go mod download
          go run ./... --is_test_build

  lint_go:
    name: Go Lint
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 100
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install golangci-lint
        run: |
          curl -sSfL https://github.com/golangci/golangci-lint/releases/download/v1.63.4/golangci-lint-1.63.4-linux-amd64.tar.gz \
            | tar -xzv -C /tmp
          mv /tmp/golangci-lint-*/golangci-lint /usr/local/bin/
          chmod +x /usr/local/bin/golangci-lint

      - name: Run Go Linter
        run: |
          cd src
          golangci-lint cache clean
          golangci-lint run ./internal/... \
            --config ./golangci.yaml \
            --skip-dirs=src/runtime \
            --max-same-issues 5 -v

  lint_sql:
    name: SQL Lint
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js & install sql-lint
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install -g sql-lint

      - name: Run SQL Linter
        run: |
          cd src
          sql-lint --ignore-errors=my-sql-invalid-create-option,my-sql-invalid-drop-option migrations/*.sql

  test:
    name: Unit Tests
    runs-on: ubuntu-24.04
    needs:
      - lint_go
      - lint_sql
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Unit Tests
        run: |
          cd src
          make unit
  deploy:
    runs-on: ubuntu-latest
    needs:
      - test
      - lint_sql
      - lint_go
      - build
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        working-directory: src
        run: |
          docker build -t skullduggerysys/filmsbot:latest .

      - name: Log in to Docker Hub
        run: |
          docker login -u artyombarskov@gmail.com -p w0nk9PZTM

      - name: Push Docker image
        run: |
          docker push skullduggerysys/filmsbot:latest
